name: Rebuild python virtual env

on:
  create:
    tags:
      - v*
  push:
    branches: [ build-venv ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: install requirements
        run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

      - name: prep
        run: sudo mkdir -p /var/www/html

      - name: chown
        run: sudo chown `id -u`:`id -g` /var/www/html

      - name: Copy files
        run: cp -r * /var/www/html

      - name: Create env
        run: cd /var/www/html; make venv

      - name: Create archive
        run: cd /var/www/html; tar -czf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}_venv_${{ env.RELEASE_VERSION }}.tar.gz .venv

      - name: Upload venv tar
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.event.repository.name }}_venv_${{ env.RELEASE_VERSION }}
          path: ${{ github.event.repository.name }}_venv_${{ env.RELEASE_VERSION }}.tar.gz
