name: Rebuild python virtual env

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: [ '3.10','3.11.2' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set env
        run: |
          echo "PKG_NAME=`basename $GITHUB_REPOSITORY -private`" >> $GITHUB_ENV
          echo "PIP_NO_BINARY=xmlsec,lxml" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxmlsec1-dev pkg-config

      - name: Build venv package
        uses: minvws/action-python-venv-package@v1
        with:
          python_version: ${{ matrix.python_version }}
          package_file_name: ${{ env.PKG_NAME }}
