name: Public repo sync

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  sync-public:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Run SSH agent
      run: |
        eval "$(ssh-agent -s)"
        echo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" >> "$GITHUB_ENV"
        echo SSH_AGENT_PID="$SSH_AGENT_PID" >> "$GITHUB_ENV"

    - name: Add SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.REPO_SYNC_PUSH_KEY }}" > /home/runner/.ssh/github_actions
        chmod 600 /home/runner/.ssh/github_actions
        ssh-add /home/runner/.ssh/github_actions

    - name: Sync repo
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
        if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then exit 1; fi

        git config --unset-all http.https://github.com/.extraheader
        git remote add public git@github.com:minvws/nl-uzipoc-register-api.git
        git push --tags public $GITHUB_REF_NAME
