name: Public repo sync

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  sync-public:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Add SSH key
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.REPO_SYNC_PUSH_KEY }}" > /home/runner/.ssh/github_actions
          chmod 600 /home/runner/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions

    - name: Sync repo
      run: |
        git --version
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "<>"
        if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then exit 1; fi

        git config --unset-all http.https://github.com/.extraheader
        git remote add public git@github.com:minvws/nl-uzipoc-register-api.git
        git push public $GITHUB_REF_NAME
